#!/usr/bin/bash

export PGPASSWORD="fgpw"

if [ "$1" == "init" ]; then
    echo "Initializing flaskgur schema."
    psql -h localhost -U fguser -d fgschema <<EOF
CREATE TABLE fgPics (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    extension TEXT NOT NULL );
EOF
elif [ "$1" == "query" ]; then
    psql -h localhost -U fguser -d fgschema
elif [ "$1" == "destroy" ]; then
    echo "Destroying flaskgur schema."
    psql -h localhost -U fguser -d fgschema <<EOF
DROP TABLE IF EXISTS fgPics;
EOF
else
    echo "fgdb init|query|destroy"
fi
